/** One original line per gestational week (LMP-dated). Index = week number. */
export const PREGNANCY_WEEKS: string[] = [
  'Week 0 — counted from your last period; conception is still ahead.',
  'Week 1 — the body prepares a fresh uterine lining.',
  'Week 2 — ovulation approaches; fertilization typically happens near the end of this week.',
  'Week 3 — a fertilized egg divides on its way to the uterus.',
  'Week 4 — implantation; a home test may now turn positive.',
  'Week 5 — early brain, spine, and cardiac structures are beginning to develop.',
  'Week 6 — about the size of a lentil; early nausea often arrives.',
  'Week 7 — limb buds sprout; the brain grows fast.',
  'Week 8 — fingers and toes take shape; fatigue peaks for many.',
  'Week 9 — officially a fetus now; all major organs have started.',
  'Week 10 — organs and body structures continue developing rather than changing on an exact date.',
  'Week 11 — about the size of a fig; the head is nearly half the body.',
  'Week 12 — reflexes appear; many people share the news after this week.',
  'Week 13 — the first trimester is nearing its close; symptoms may ease, persist, or change.',
  'Week 14 — the roof of the mouth closes; expressions flicker.',
  'Week 15 — bones harden; the scalp pattern is set.',
  'Week 16 — about the size of an avocado; you may feel flutters soon.',
  'Week 17 — the skeleton shifts from cartilage to bone.',
  'Week 18 — ears are in place; loud sounds may register.',
  'Week 19 — a protective coating (vernix) covers the skin.',
  'Week 20 — halfway; the anatomy scan usually happens now.',
  'Week 21 — movements become unmistakable kicks.',
  'Week 22 — about the size of a papaya; eyebrows are in.',
  'Week 23 — hearing sharpens; your voice is the soundtrack.',
  'Week 24 — movement and lung development continue; individual medical outlook depends on many factors.',
  'Week 25 — responds to light and sound with movement.',
  'Week 26 — eyes open for the first time.',
  'Week 27 — the second trimester is nearing its close; sleep and comfort may shift.',
  'Week 28 — regular kick patterns emerge; many clinicians suggest counting them.',
  'Week 29 — rapid brain growth; the head grows to match.',
  'Week 30 — about the size of a cabbage; practice contractions may start.',
  'Week 31 — fat accumulates; skin smooths out.',
  'Week 32 — many babies settle head-down around now.',
  'Week 33 — bones firm up, except the flexible skull.',
  'Week 34 — the immune system stocks up on your antibodies.',
  'Week 35 — growth and lung, brain, and nervous-system development continue.',
  'Week 36 — "early term" is one week away; bag-packing territory.',
  'Week 37 — early term; labor could reasonably start any time.',
  'Week 38 — full term approaches; the brain is still wiring furiously.',
  'Week 39 — full term; the due date is an estimate, not an appointment.',
  'Week 40 — the classic finish line; only about 1 in 20 arrive exactly on it.',
]
